# Generated by Django 5.0.1 on 2024-02-05 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
    ]
