# Generated by Django 5.0.1 on 2024-02-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_comment_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="login_required",
            field=models.BooleanField(default=False),
        ),
    ]
