# Generated by Django 5.0.1 on 2024-02-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_post_login_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
